# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Skill(models.Model):
    BRANCHES = (
        ('Red', 'Red'),
        ('Yellow', 'Yellow'),
        ('Blue', 'Blue'),
        ('Green', 'Green'),
    )
    id = models.CharField(max_length=255, primary_key=True)
    branch = models.CharField(choices=BRANCHES,max_length=6)
    slot = models.IntegerField(null=True, blank=True)
    sp_req = models.IntegerField(null=True, blank=True)
    skill_req = models.CharField(max_length=255, null=True, blank=True)
    tier = models.CharField(max_length=3)
    name = models.CharField(max_length=255)
    note = models.CharField(max_length=255)
    max_level = models.IntegerField(null=True, blank=True)
    stage = models.IntegerField(null=True, blank=True)
    cost_lvl0 = models.IntegerField(null=True, blank=True)
    cost_lvl1 = models.IntegerField(null=True, blank=True)
    cost_lvl2 = models.IntegerField(null=True, blank=True)
    cost_lvl3 = models.IntegerField(null=True, blank=True)
    cost_lvl4 = models.IntegerField(null=True, blank=True)
    cost_lvl5 = models.IntegerField(null=True, blank=True)
    cost_lvl6 = models.IntegerField(null=True, blank=True)
    cost_lvl7 = models.IntegerField(null=True, blank=True)
    cost_lvl8 = models.IntegerField(null=True, blank=True)
    cost_lvl9 = models.IntegerField(null=True, blank=True)
    cost_lvl10 = models.IntegerField(null=True, blank=True)
    cost_lvl11 = models.IntegerField(null=True, blank=True)
    cost_lvl12 = models.IntegerField(null=True, blank=True)
    cost_lvl13 = models.IntegerField(null=True, blank=True)
    cost_lvl14 = models.IntegerField(null=True, blank=True)
    cost_lvl15 = models.IntegerField(null=True, blank=True)
    cost_lvl16 = models.IntegerField(null=True, blank=True)
    cost_lvl17 = models.IntegerField(null=True, blank=True)
    cost_lvl18 = models.IntegerField(null=True, blank=True)
    cost_lvl19 = models.IntegerField(null=True, blank=True)
    cost_lvl20 = models.IntegerField(null=True, blank=True)
    bonus_effect1_text = models.CharField(max_length=255)
    bonus_effect1_lvl1 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl2 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl3 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl4 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl5 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl6 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl7 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl8 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl9 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl10 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl11 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl12 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl13 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl14 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl15 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl16 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl17 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl18 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl19 = models.FloatField(null=True, blank=True)
    bonus_effect1_lvl20 = models.FloatField(null=True, blank=True)
    bonus_effect2_text = models.CharField(max_length=255)
    bonus_effect2_lvl1 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl2 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl3 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl4 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl5 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl6 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl7 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl8 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl9 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl10 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl11 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl12 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl13 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl14 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl15 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl16 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl17 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl18 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl19 = models.FloatField(null=True, blank=True)
    bonus_effect2_lvl20 = models.FloatField(null=True, blank=True)
