# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=6)),
                ('slot', models.IntegerField()),
                ('sp_req', models.IntegerField()),
                ('tier', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('max_level', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('cost_lvl0', models.IntegerField()),
                ('cost_lvl1', models.IntegerField()),
                ('cost_lvl2', models.IntegerField()),
                ('cost_lvl3', models.IntegerField()),
                ('cost_lvl4', models.IntegerField()),
                ('cost_lvl5', models.IntegerField()),
                ('cost_lvl6', models.IntegerField()),
                ('cost_lvl7', models.IntegerField()),
                ('cost_lvl8', models.IntegerField()),
                ('cost_lvl9', models.IntegerField()),
                ('cost_lvl10', models.IntegerField()),
                ('cost_lvl11', models.IntegerField()),
                ('cost_lvl12', models.IntegerField()),
                ('cost_lvl13', models.IntegerField()),
                ('cost_lvl14', models.IntegerField()),
                ('cost_lvl15', models.IntegerField()),
                ('cost_lvl16', models.IntegerField()),
                ('cost_lvl17', models.IntegerField()),
                ('cost_lvl18', models.IntegerField()),
                ('cost_lvl19', models.IntegerField()),
                ('cost_lvl20', models.IntegerField()),
                ('bonus_effect1_text', models.CharField(max_length=255)),
                ('bonus_effect1_lvl1', models.FloatField()),
                ('bonus_effect1_lvl2', models.FloatField()),
                ('bonus_effect1_lvl3', models.FloatField()),
                ('bonus_effect1_lvl4', models.FloatField()),
                ('bonus_effect1_lvl5', models.FloatField()),
                ('bonus_effect1_lvl6', models.FloatField()),
                ('bonus_effect1_lvl7', models.FloatField()),
                ('bonus_effect1_lvl8', models.FloatField()),
                ('bonus_effect1_lvl9', models.FloatField()),
                ('bonus_effect1_lvl10', models.FloatField()),
                ('bonus_effect1_lvl11', models.FloatField()),
                ('bonus_effect1_lvl12', models.FloatField()),
                ('bonus_effect1_lvl13', models.FloatField()),
                ('bonus_effect1_lvl14', models.FloatField()),
                ('bonus_effect1_lvl15', models.FloatField()),
                ('bonus_effect1_lvl16', models.FloatField()),
                ('bonus_effect1_lvl17', models.FloatField()),
                ('bonus_effect1_lvl18', models.FloatField()),
                ('bonus_effect1_lvl19', models.FloatField()),
                ('bonus_effect1_lvl20', models.FloatField()),
                ('bonus_effect2_text', models.CharField(max_length=255)),
                ('bonus_effect2_lvl1', models.FloatField()),
                ('bonus_effect2_lvl2', models.FloatField()),
                ('bonus_effect2_lvl3', models.FloatField()),
                ('bonus_effect2_lvl4', models.FloatField()),
                ('bonus_effect2_lvl5', models.FloatField()),
                ('bonus_effect2_lvl6', models.FloatField()),
                ('bonus_effect2_lvl7', models.FloatField()),
                ('bonus_effect2_lvl8', models.FloatField()),
                ('bonus_effect2_lvl9', models.FloatField()),
                ('bonus_effect2_lvl10', models.FloatField()),
                ('bonus_effect2_lvl11', models.FloatField()),
                ('bonus_effect2_lvl12', models.FloatField()),
                ('bonus_effect2_lvl13', models.FloatField()),
                ('bonus_effect2_lvl14', models.FloatField()),
                ('bonus_effect2_lvl15', models.FloatField()),
                ('bonus_effect2_lvl16', models.FloatField()),
                ('bonus_effect2_lvl17', models.FloatField()),
                ('bonus_effect2_lvl18', models.FloatField()),
                ('bonus_effect2_lvl19', models.FloatField()),
                ('bonus_effect2_lvl20', models.FloatField()),
                ('skill_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
    ]
