# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20171030_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_req',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
